name: tharad_app
description: "A new Flutter project."

publish_to: 'none'


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  clipboard: ^2.0.2
  pin_code_fields: ^8.0.1
  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  dotted_border: ^2.0.0
  image_picker: ^1.2.1





  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/png/
    - assets/fonts/





  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

